modLoader="javafml"
loaderVersion="[34,)"
license="GNU LGPL 3.0"
issueTrackerURL="https://github.com/Eltrut-Co/More-Respawn-Anchors/issues"
[[mods]]
modId="morerespawnanchors"
version="1.0.0"
displayName="More Respawn Anchors"
logoFile="morerespawnanchors.png"
credits="cominixo, EltrutLikes"
authors="Eltrut & Co."
description='''
'''

[[dependencies.morerespawnanchors]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morerespawnanchors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.morerespawnanchors]]
    modId="differentiate"
    mandatory=true
    versionRange="[0.3.2,)"
    ordering="AFTER"
    side="BOTH"